services:
  - type: web
    name: autenticacion-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn autenticacion.wsgi:application"
    branch: main
